This is HW_4
azartnyi/JS_HW pull request #2
Opened 2024-05-29 21:06 UTC by azartnyi

Hello, check please <3
![image](https://github.com/azartnyi/JS_HW/assets/83118035/d5b403e9-8db1-4f0b-b5e7-9cbf3d0cc870)

2024-05-29 21:55 UTC, VladimirLQA requested changes

2024-05-29 21:55 UTC, VladimirLQA commented on HW_4/html+js/hw4_3.js
> +let minAge = 18;
Use `const` whenever possible

2024-05-29 21:55 UTC, VladimirLQA commented on HW_4/hw4_1_2.js
> +//Task 1
Add descriptions for tasks

2024-05-29 21:55 UTC, VladimirLQA commented on HW_4/hw4_1_2.js
> +//Task 2
Some tasks can have subtasks with modifications to previous !

2024-05-30 19:10 UTC, azartnyi commented on HW_4/hw4_1_2.js
> +//Task 1
fixed

2024-05-30 19:10 UTC, azartnyi commented on HW_4/hw4_1_2.js
> +//Task 2
fixed

2024-05-30 21:07 UTC, anatoly-karpovich approved these changes

2024-05-31 02:03 UTC, merged